import { db } from "@workspace/db";
import { categoriesTable, productsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

const categories = [
  {
    name: "Electronics",
    slug: "electronics",
    description: "Latest gadgets and tech devices",
    imageUrl: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&auto=format&fit=crop",
  },
  {
    name: "Clothing",
    slug: "clothing",
    description: "Fashion for every occasion",
    imageUrl: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=600&auto=format&fit=crop",
  },
  {
    name: "Home & Living",
    slug: "home-living",
    description: "Decor and essentials for your home",
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop",
  },
  {
    name: "Sports & Outdoors",
    slug: "sports",
    description: "Gear for active lifestyles",
    imageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&auto=format&fit=crop",
  },
  {
    name: "Beauty",
    slug: "beauty",
    description: "Skincare, makeup and wellness",
    imageUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop",
  },
  {
    name: "Books",
    slug: "books",
    description: "Fiction, non-fiction, and more",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop",
  },
];

const productSeed = [
  {
    categorySlug: "electronics",
    name: "Wireless Noise-Cancelling Headphones",
    description: "Premium over-ear headphones with 40-hour battery life, active noise cancellation, and superior sound quality. Perfect for work-from-home, commuting, or just enjoying your favorite music.",
    price: "249.99",
    originalPrice: "329.99",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop"],
    stock: 45,
    rating: "4.8",
    reviewCount: 1284,
    isFeatured: true,
    isNew: false,
    badge: "24% OFF",
    tags: ["audio", "wireless", "noise-cancelling"],
  },
  {
    categorySlug: "electronics",
    name: "Smart Watch Pro",
    description: "Feature-packed smartwatch with health monitoring, GPS, 5-day battery life, and a stunning AMOLED display. Tracks workouts, sleep, heart rate and more.",
    price: "399.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop"],
    stock: 28,
    rating: "4.6",
    reviewCount: 892,
    isFeatured: true,
    isNew: true,
    badge: "New",
    tags: ["wearable", "fitness", "smartwatch"],
  },
  {
    categorySlug: "electronics",
    name: "Mechanical Gaming Keyboard",
    description: "RGB backlit mechanical keyboard with tactile switches, anti-ghosting, and a durable aluminum frame. Designed for gamers who demand precision.",
    price: "129.99",
    originalPrice: "159.99",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop"],
    stock: 60,
    rating: "4.7",
    reviewCount: 543,
    isFeatured: false,
    isNew: false,
    badge: "19% OFF",
    tags: ["gaming", "keyboard", "RGB"],
  },
  {
    categorySlug: "electronics",
    name: "Portable Bluetooth Speaker",
    description: "360-degree sound, IPX7 waterproof, 24-hour playtime. Take the music everywhere — beach, hikes, camping. Pairs seamlessly with any device.",
    price: "89.99",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop"],
    stock: 80,
    rating: "4.5",
    reviewCount: 723,
    isFeatured: false,
    isNew: true,
    badge: "New",
    tags: ["audio", "portable", "waterproof"],
  },
  {
    categorySlug: "clothing",
    name: "Classic Fit Oxford Shirt",
    description: "Crafted from 100% premium cotton, this timeless Oxford shirt transitions effortlessly from office to weekend. Available in multiple colors with a flattering classic fit.",
    price: "59.99",
    originalPrice: "79.99",
    imageUrl: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&auto=format&fit=crop"],
    stock: 120,
    rating: "4.4",
    reviewCount: 387,
    isFeatured: true,
    isNew: false,
    badge: "25% OFF",
    tags: ["shirt", "oxford", "formal"],
  },
  {
    categorySlug: "clothing",
    name: "Performance Running Jacket",
    description: "Lightweight, windproof and water-resistant running jacket. Packable design, reflective details, and ventilated mesh lining keep you comfortable on every run.",
    price: "110.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop"],
    stock: 55,
    rating: "4.6",
    reviewCount: 214,
    isFeatured: false,
    isNew: true,
    badge: "New",
    tags: ["running", "jacket", "outdoor"],
  },
  {
    categorySlug: "clothing",
    name: "Premium Denim Jeans",
    description: "Slim-fit jeans made from sustainable denim. Four-way stretch fabric for all-day comfort. Classic five-pocket styling with a modern tapered leg.",
    price: "85.00",
    originalPrice: "105.00",
    imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&auto=format&fit=crop"],
    stock: 95,
    rating: "4.3",
    reviewCount: 654,
    isFeatured: false,
    isNew: false,
    badge: "19% OFF",
    tags: ["jeans", "denim", "slim-fit"],
  },
  {
    categorySlug: "home-living",
    name: "Ceramic Pour-Over Coffee Set",
    description: "Beautifully handcrafted ceramic pour-over dripper and server set. Brew barista-quality coffee at home with this elegant and functional coffee set.",
    price: "68.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop"],
    stock: 40,
    rating: "4.9",
    reviewCount: 189,
    isFeatured: true,
    isNew: false,
    badge: null,
    tags: ["coffee", "ceramic", "kitchen"],
  },
  {
    categorySlug: "home-living",
    name: "Linen Throw Blanket",
    description: "Ultra-soft woven linen throw blanket, perfect for cozy evenings. Lightweight yet warm, with a beautiful textured weave that looks great on any sofa.",
    price: "49.99",
    originalPrice: "65.00",
    imageUrl: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=600&auto=format&fit=crop"],
    stock: 70,
    rating: "4.7",
    reviewCount: 302,
    isFeatured: false,
    isNew: false,
    badge: "23% OFF",
    tags: ["linen", "blanket", "home"],
  },
  {
    categorySlug: "home-living",
    name: "Scented Soy Candle Collection",
    description: "Set of 3 hand-poured soy candles with calming botanical scents: Cedarwood & Sage, Lavender Fields, and Citrus Grove. Up to 45 hours burn time each.",
    price: "38.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop"],
    stock: 85,
    rating: "4.8",
    reviewCount: 456,
    isFeatured: false,
    isNew: true,
    badge: "New",
    tags: ["candle", "soy", "scented"],
  },
  {
    categorySlug: "sports",
    name: "Yoga Mat Pro",
    description: "Premium non-slip yoga mat with alignment markings, eco-friendly materials, and extra thickness for joint support. Comes with a carry strap.",
    price: "79.00",
    originalPrice: "99.00",
    imageUrl: "https://images.unsplash.com/photo-1601925228081-44b769474f2f?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1601925228081-44b769474f2f?w=600&auto=format&fit=crop"],
    stock: 90,
    rating: "4.8",
    reviewCount: 834,
    isFeatured: true,
    isNew: false,
    badge: "20% OFF",
    tags: ["yoga", "fitness", "mat"],
  },
  {
    categorySlug: "sports",
    name: "Adjustable Dumbbell Set",
    description: "Space-saving adjustable dumbbells from 5 to 52.5 lbs per dumbbell. Replace 15 sets of weights. Dial-select system adjusts in seconds.",
    price: "349.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&auto=format&fit=crop"],
    stock: 20,
    rating: "4.9",
    reviewCount: 1102,
    isFeatured: false,
    isNew: false,
    badge: null,
    tags: ["weights", "dumbbells", "gym"],
  },
  {
    categorySlug: "beauty",
    name: "Vitamin C Brightening Serum",
    description: "Powerful 20% Vitamin C serum with Hyaluronic Acid and Vitamin E. Brightens skin tone, reduces dark spots and delivers a radiant, youthful glow.",
    price: "45.00",
    originalPrice: "60.00",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop"],
    stock: 110,
    rating: "4.6",
    reviewCount: 978,
    isFeatured: true,
    isNew: false,
    badge: "25% OFF",
    tags: ["skincare", "serum", "vitamin-c"],
  },
  {
    categorySlug: "beauty",
    name: "Natural Face Moisturizer SPF 30",
    description: "Lightweight daily moisturizer with broad-spectrum SPF 30. Non-greasy formula packed with niacinamide, ceramides, and antioxidants for healthy, protected skin.",
    price: "32.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop"],
    stock: 130,
    rating: "4.5",
    reviewCount: 612,
    isFeatured: false,
    isNew: true,
    badge: "New",
    tags: ["skincare", "moisturizer", "SPF"],
  },
  {
    categorySlug: "books",
    name: "Atomic Habits",
    description: "An Easy and Proven Way to Build Good Habits and Break Bad Ones by James Clear. The #1 New York Times bestseller with over 10 million copies sold worldwide.",
    price: "18.99",
    originalPrice: "27.00",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop"],
    stock: 200,
    rating: "4.9",
    reviewCount: 5421,
    isFeatured: false,
    isNew: false,
    badge: "30% OFF",
    tags: ["self-help", "habits", "productivity"],
  },
  {
    categorySlug: "books",
    name: "The Creative Act",
    description: "A Way of Being by Rick Rubin. A profound exploration of creativity from the legendary music producer. A book for artists and anyone who wants to live a more creative life.",
    price: "22.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop"],
    stock: 150,
    rating: "4.7",
    reviewCount: 2134,
    isFeatured: false,
    isNew: false,
    badge: null,
    tags: ["creativity", "art", "inspiration"],
  },
];

async function seed() {
  console.log("Seeding database...");

  await db.execute(sql`TRUNCATE TABLE order_items, orders, cart_items, products, categories RESTART IDENTITY CASCADE`);

  const insertedCategories = await db.insert(categoriesTable).values(categories).returning();
  console.log(`Inserted ${insertedCategories.length} categories`);

  const categoryMap = new Map(insertedCategories.map(c => [c.slug, c.id]));

  const productsWithIds = productSeed.map(({ categorySlug, ...p }) => ({
    ...p,
    categoryId: categoryMap.get(categorySlug)!,
  }));

  const insertedProducts = await db.insert(productsTable).values(productsWithIds).returning();
  console.log(`Inserted ${insertedProducts.length} products`);

  console.log("Seeding complete!");
}

seed().catch(console.error);
